# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title:  Beomsu Kim's Blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Beomsu Kim's Blog

description: Stylish Jekyll Theme
author:
  name: Beomsu Kim
  email: 123bskim@naver.com
  github: shuuki4
  twitter: shuuki4
  pinterest: abc
  linkedin: abc
  bio: Beomsu Kim / YuKiSa
  email_md5: 09bd047fc24f8cabab634c94bafbfca9

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate